title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

# baseurl: "/workbook-jk"
# url: "https://johnydotsville.github.io"
url: https://johnydotsville.github.io/workbook-jk

aux_links:
  Template Repository: https://johnydotsville.github.io/workbook-jk
